# Generated by Django 3.2.6 on 2021-08-25 07:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=100)),
                ('address_name_detail', models.CharField(max_length=100)),
                ('address_type', models.CharField(max_length=11)),
                ('address_coord', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='AddressRegion',
            fields=[
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.address')),
                ('address_name', models.CharField(max_length=100)),
                ('region_1depth_name', models.CharField(max_length=20)),
                ('region_2depth_name', models.CharField(max_length=20)),
                ('region_3depth_name', models.CharField(max_length=20)),
                ('region_3depth_h_name', models.CharField(max_length=20)),
                ('h_code', models.CharField(max_length=10)),
                ('b_code', models.CharField(max_length=10)),
                ('mountain_yn', models.CharField(max_length=1)),
                ('main_address_no', models.CharField(max_length=10)),
                ('sub_address_no', models.CharField(max_length=10)),
                ('address_coord', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='AddressRoad',
            fields=[
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.address')),
                ('address_name', models.CharField(max_length=100)),
                ('region_1depth_name', models.CharField(max_length=20)),
                ('region_2depth_name', models.CharField(max_length=20)),
                ('region_3depth_name', models.CharField(max_length=20)),
                ('road_name', models.CharField(max_length=20)),
                ('underground_yn', models.CharField(max_length=1)),
                ('main_building_no', models.CharField(max_length=10)),
                ('sub_building_no', models.CharField(max_length=10)),
                ('building_name', models.CharField(max_length=30)),
                ('zone_no', models.CharField(max_length=5)),
                ('address_coord', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=20)),
                ('uuid', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.address')),
                ('animals', models.ManyToManyField(to='accounts.Animal')),
            ],
        ),
    ]
