# Generated by Django 3.2.6 on 2021-08-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bemybaby', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bemybaby',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
