# Generated by Django 3.2.6 on 2021-08-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bemybaby', '0002_bemybaby_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BeMyBabyComment',
        ),
    ]
