# Generated by Django 3.2.6 on 2021-08-11 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bemybaby', '0003_delete_bemybabycomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeMyBabyComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bemybaby.bemybaby')),
            ],
        ),
    ]
