# Generated by Django 3.2.6 on 2021-08-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bemybaby', '0004_bemybabycomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bemybabycomment',
            old_name='feed',
            new_name='bemybaby',
        ),
    ]
